// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package database

import (
	"context"
)

const getDashboardKPIs = `-- name: GetDashboardKPIs :one
SELECT
    -- Vehicle KPIs
    COUNT(v.id)                                                    AS total_vehicles,
    COUNT(v.id) FILTER (WHERE v.status = 'Available')              AS available_vehicles,
    COUNT(v.id) FILTER (WHERE v.status = 'On Trip')                AS active_vehicles,
    COUNT(v.id) FILTER (WHERE v.status = 'In Shop')                AS vehicles_in_maintenance,
    COUNT(v.id) FILTER (WHERE v.status = 'Retired')                AS retired_vehicles,

    -- Fleet Utilization = (On Trip) / (Total - Retired) * 100
    -- COALESCE to 0 if there are no non-retired vehicles to avoid division by zero
    COALESCE(
        ROUND(
            COUNT(v.id) FILTER (WHERE v.status = 'On Trip') * 100.0
            / NULLIF(COUNT(v.id) FILTER (WHERE v.status != 'Retired'), 0),
            1
        ), 0
    )                                                              AS fleet_utilization_pct,

    -- Trip KPIs (subqueries to avoid cross-join multiplication)
    (SELECT COUNT(*) FROM trips WHERE status = 'Dispatched')       AS active_trips,
    (SELECT COUNT(*) FROM trips WHERE status = 'Draft')            AS pending_trips,
    (SELECT COUNT(*) FROM trips WHERE status = 'Completed')        AS completed_trips,

    -- Driver KPIs
    (SELECT COUNT(*) FROM drivers WHERE status = 'On Trip')        AS drivers_on_duty,
    (SELECT COUNT(*) FROM drivers WHERE status = 'Available')      AS available_drivers,
    (SELECT COUNT(*) FROM drivers)                                 AS total_drivers
FROM vehicles v
`

type GetDashboardKPIsRow struct {
	TotalVehicles         int64
	AvailableVehicles     int64
	ActiveVehicles        int64
	VehiclesInMaintenance int64
	RetiredVehicles       int64
	FleetUtilizationPct   interface{}
	ActiveTrips           int64
	PendingTrips          int64
	CompletedTrips        int64
	DriversOnDuty         int64
	AvailableDrivers      int64
	TotalDrivers          int64
}

// Single query that computes all dashboard KPIs using conditional aggregation.
// This avoids N+1 round trips to the database.
func (q *Queries) GetDashboardKPIs(ctx context.Context) (GetDashboardKPIsRow, error) {
	row := q.db.QueryRowContext(ctx, getDashboardKPIs)
	var i GetDashboardKPIsRow
	err := row.Scan(
		&i.TotalVehicles,
		&i.AvailableVehicles,
		&i.ActiveVehicles,
		&i.VehiclesInMaintenance,
		&i.RetiredVehicles,
		&i.FleetUtilizationPct,
		&i.ActiveTrips,
		&i.PendingTrips,
		&i.CompletedTrips,
		&i.DriversOnDuty,
		&i.AvailableDrivers,
		&i.TotalDrivers,
	)
	return i, err
}
