// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: expenses.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createExpense = `-- name: CreateExpense :one
INSERT INTO expenses (vehicle_id, category, amount, expense_date, description)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, vehicle_id, category, amount, expense_date, description, created_at
`

type CreateExpenseParams struct {
	VehicleID   uuid.UUID
	Category    string
	Amount      string
	ExpenseDate time.Time
	Description sql.NullString
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error) {
	row := q.db.QueryRowContext(ctx, createExpense,
		arg.VehicleID,
		arg.Category,
		arg.Amount,
		arg.ExpenseDate,
		arg.Description,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.Category,
		&i.Amount,
		&i.ExpenseDate,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getAllExpenses = `-- name: GetAllExpenses :many
SELECT id, vehicle_id, category, amount, expense_date, description, created_at FROM expenses
ORDER BY expense_date DESC
`

func (q *Queries) GetAllExpenses(ctx context.Context) ([]Expense, error) {
	rows, err := q.db.QueryContext(ctx, getAllExpenses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.Category,
			&i.Amount,
			&i.ExpenseDate,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExpensesByVehicle = `-- name: GetExpensesByVehicle :many
SELECT id, vehicle_id, category, amount, expense_date, description, created_at FROM expenses
WHERE vehicle_id = $1
ORDER BY expense_date DESC
`

func (q *Queries) GetExpensesByVehicle(ctx context.Context, vehicleID uuid.UUID) ([]Expense, error) {
	rows, err := q.db.QueryContext(ctx, getExpensesByVehicle, vehicleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.Category,
			&i.Amount,
			&i.ExpenseDate,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
