// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fuel_logs.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFuelLog = `-- name: CreateFuelLog :one
INSERT INTO fuel_logs (vehicle_id, liters, cost, log_date)
VALUES ($1, $2, $3, $4)
RETURNING id, vehicle_id, liters, cost, log_date, created_at
`

type CreateFuelLogParams struct {
	VehicleID uuid.NullUUID
	Liters    string
	Cost      string
	LogDate   time.Time
}

func (q *Queries) CreateFuelLog(ctx context.Context, arg CreateFuelLogParams) (FuelLog, error) {
	row := q.db.QueryRowContext(ctx, createFuelLog,
		arg.VehicleID,
		arg.Liters,
		arg.Cost,
		arg.LogDate,
	)
	var i FuelLog
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.Liters,
		&i.Cost,
		&i.LogDate,
		&i.CreatedAt,
	)
	return i, err
}

const getAllFuelLogs = `-- name: GetAllFuelLogs :many
SELECT id, vehicle_id, liters, cost, log_date, created_at FROM fuel_logs
ORDER BY log_date DESC
`

func (q *Queries) GetAllFuelLogs(ctx context.Context) ([]FuelLog, error) {
	rows, err := q.db.QueryContext(ctx, getAllFuelLogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FuelLog
	for rows.Next() {
		var i FuelLog
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.Liters,
			&i.Cost,
			&i.LogDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFuelLogsByVehicle = `-- name: GetFuelLogsByVehicle :many
SELECT id, vehicle_id, liters, cost, log_date, created_at FROM fuel_logs
WHERE vehicle_id = $1
ORDER BY log_date DESC
`

func (q *Queries) GetFuelLogsByVehicle(ctx context.Context, vehicleID uuid.NullUUID) ([]FuelLog, error) {
	rows, err := q.db.QueryContext(ctx, getFuelLogsByVehicle, vehicleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FuelLog
	for rows.Next() {
		var i FuelLog
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.Liters,
			&i.Cost,
			&i.LogDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOperationalCostPerVehicle = `-- name: GetOperationalCostPerVehicle :many
WITH fuel_agg AS (
    SELECT
        vehicle_id,
        COALESCE(SUM(cost), 0)   AS total_fuel_cost,
        COALESCE(SUM(liters), 0) AS total_liters
    FROM fuel_logs
    GROUP BY vehicle_id
),
maintenance_agg AS (
    SELECT
        vehicle_id,
        COALESCE(SUM(cost), 0) AS total_maintenance_cost
    FROM maintenance_logs
    GROUP BY vehicle_id
),
expense_agg AS (
    SELECT
        vehicle_id,
        COALESCE(SUM(amount), 0) AS total_other_expenses
    FROM expenses
    GROUP BY vehicle_id
),
trip_agg AS (
    SELECT
        vehicle_id,
        COALESCE(SUM(planned_distance), 0) AS total_distance
    FROM trips
    WHERE status = 'Completed'
    GROUP BY vehicle_id
)
SELECT
    v.id                                                          AS vehicle_id,
    v.registration_number,
    v.name_model,
    v.acquisition_cost,

    -- Individual cost buckets
    COALESCE(f.total_fuel_cost, 0)                                AS total_fuel_cost,
    COALESCE(m.total_maintenance_cost, 0)                         AS total_maintenance_cost,
    COALESCE(e.total_other_expenses, 0)                           AS total_other_expenses,

    -- Total Operational Cost = Fuel + Maintenance + Other
    (COALESCE(f.total_fuel_cost, 0)
     + COALESCE(m.total_maintenance_cost, 0)
     + COALESCE(e.total_other_expenses, 0))                       AS total_operational_cost,

    -- Fuel Efficiency = Total Distance / Total Liters (km/L or mi/gal)
    CASE
        WHEN COALESCE(f.total_liters, 0) > 0
        THEN ROUND(COALESCE(t.total_distance, 0) / f.total_liters, 2)
        ELSE 0
    END                                                           AS fuel_efficiency,

    -- Vehicle ROI = (Revenue − (Maintenance + Fuel)) / Acquisition Cost
    -- Revenue is not tracked yet, so we show cost-based ROI as negative ratio
    -- ROI = −(Fuel + Maintenance) / Acquisition Cost  (lower is better)
    CASE
        WHEN v.acquisition_cost > 0
        THEN ROUND(
            -(COALESCE(f.total_fuel_cost, 0) + COALESCE(m.total_maintenance_cost, 0))
            / v.acquisition_cost, 4
        )
        ELSE 0
    END                                                           AS cost_roi

FROM vehicles v
LEFT JOIN fuel_agg        f ON f.vehicle_id = v.id
LEFT JOIN maintenance_agg m ON m.vehicle_id = v.id
LEFT JOIN expense_agg     e ON e.vehicle_id = v.id
LEFT JOIN trip_agg        t ON t.vehicle_id = v.id
ORDER BY total_operational_cost DESC
`

type GetOperationalCostPerVehicleRow struct {
	VehicleID            uuid.UUID
	RegistrationNumber   string
	NameModel            string
	AcquisitionCost      string
	TotalFuelCost        interface{}
	TotalMaintenanceCost interface{}
	TotalOtherExpenses   interface{}
	TotalOperationalCost int32
	FuelEfficiency       int32
	CostRoi              int32
}

// ──────────────────────────────────────────────────────────────────────────────
// Operational Cost per Vehicle (single query, O(n) scan)
//
// Uses CTEs to pre-aggregate each cost source independently, then joins once.
// This avoids the classic N×M cross-join explosion from joining fuel_logs ×
// maintenance_logs × expenses directly.
//
// Time complexity: O(F + M + E + V) where
//
//	F = fuel_log rows, M = maintenance rows, E = expense rows, V = vehicle rows
//
// No nested loops, no correlated subqueries.
// ──────────────────────────────────────────────────────────────────────────────
func (q *Queries) GetOperationalCostPerVehicle(ctx context.Context) ([]GetOperationalCostPerVehicleRow, error) {
	rows, err := q.db.QueryContext(ctx, getOperationalCostPerVehicle)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOperationalCostPerVehicleRow
	for rows.Next() {
		var i GetOperationalCostPerVehicleRow
		if err := rows.Scan(
			&i.VehicleID,
			&i.RegistrationNumber,
			&i.NameModel,
			&i.AcquisitionCost,
			&i.TotalFuelCost,
			&i.TotalMaintenanceCost,
			&i.TotalOtherExpenses,
			&i.TotalOperationalCost,
			&i.FuelEfficiency,
			&i.CostRoi,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
