// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: maintenance.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const closeMaintenanceLog = `-- name: CloseMaintenanceLog :one
UPDATE maintenance_logs
SET is_active = FALSE, end_date = $2
WHERE id = $1
RETURNING id, vehicle_id, description, cost, start_date, end_date, is_active, created_at
`

type CloseMaintenanceLogParams struct {
	ID      uuid.UUID
	EndDate sql.NullTime
}

func (q *Queries) CloseMaintenanceLog(ctx context.Context, arg CloseMaintenanceLogParams) (MaintenanceLog, error) {
	row := q.db.QueryRowContext(ctx, closeMaintenanceLog, arg.ID, arg.EndDate)
	var i MaintenanceLog
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.Description,
		&i.Cost,
		&i.StartDate,
		&i.EndDate,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const createMaintenanceLog = `-- name: CreateMaintenanceLog :one
INSERT INTO maintenance_logs (vehicle_id, description, cost, start_date, is_active)
VALUES ($1, $2, $3, $4, TRUE)
RETURNING id, vehicle_id, description, cost, start_date, end_date, is_active, created_at
`

type CreateMaintenanceLogParams struct {
	VehicleID   uuid.UUID
	Description string
	Cost        string
	StartDate   time.Time
}

func (q *Queries) CreateMaintenanceLog(ctx context.Context, arg CreateMaintenanceLogParams) (MaintenanceLog, error) {
	row := q.db.QueryRowContext(ctx, createMaintenanceLog,
		arg.VehicleID,
		arg.Description,
		arg.Cost,
		arg.StartDate,
	)
	var i MaintenanceLog
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.Description,
		&i.Cost,
		&i.StartDate,
		&i.EndDate,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveMaintenanceLogs = `-- name: GetActiveMaintenanceLogs :many
SELECT id, vehicle_id, description, cost, start_date, end_date, is_active, created_at FROM maintenance_logs
WHERE is_active = TRUE
ORDER BY start_date DESC
`

func (q *Queries) GetActiveMaintenanceLogs(ctx context.Context) ([]MaintenanceLog, error) {
	rows, err := q.db.QueryContext(ctx, getActiveMaintenanceLogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MaintenanceLog
	for rows.Next() {
		var i MaintenanceLog
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.Description,
			&i.Cost,
			&i.StartDate,
			&i.EndDate,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMaintenanceLogByID = `-- name: GetMaintenanceLogByID :one
SELECT id, vehicle_id, description, cost, start_date, end_date, is_active, created_at FROM maintenance_logs
WHERE id = $1
`

func (q *Queries) GetMaintenanceLogByID(ctx context.Context, id uuid.UUID) (MaintenanceLog, error) {
	row := q.db.QueryRowContext(ctx, getMaintenanceLogByID, id)
	var i MaintenanceLog
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.Description,
		&i.Cost,
		&i.StartDate,
		&i.EndDate,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getMaintenanceLogsByVehicle = `-- name: GetMaintenanceLogsByVehicle :many
SELECT id, vehicle_id, description, cost, start_date, end_date, is_active, created_at FROM maintenance_logs
WHERE vehicle_id = $1
ORDER BY start_date DESC
`

func (q *Queries) GetMaintenanceLogsByVehicle(ctx context.Context, vehicleID uuid.UUID) ([]MaintenanceLog, error) {
	rows, err := q.db.QueryContext(ctx, getMaintenanceLogsByVehicle, vehicleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MaintenanceLog
	for rows.Next() {
		var i MaintenanceLog
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.Description,
			&i.Cost,
			&i.StartDate,
			&i.EndDate,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
