// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type DriverStatus string

const (
	DriverStatusAvailable DriverStatus = "Available"
	DriverStatusOnTrip    DriverStatus = "On Trip"
	DriverStatusOffDuty   DriverStatus = "Off Duty"
	DriverStatusSuspended DriverStatus = "Suspended"
)

func (e *DriverStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DriverStatus(s)
	case string:
		*e = DriverStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DriverStatus: %T", src)
	}
	return nil
}

type NullDriverStatus struct {
	DriverStatus DriverStatus
	Valid        bool // Valid is true if DriverStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDriverStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DriverStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DriverStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDriverStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DriverStatus), nil
}

type TripStatus string

const (
	TripStatusDraft      TripStatus = "Draft"
	TripStatusDispatched TripStatus = "Dispatched"
	TripStatusCompleted  TripStatus = "Completed"
	TripStatusCancelled  TripStatus = "Cancelled"
)

func (e *TripStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TripStatus(s)
	case string:
		*e = TripStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TripStatus: %T", src)
	}
	return nil
}

type NullTripStatus struct {
	TripStatus TripStatus
	Valid      bool // Valid is true if TripStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTripStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TripStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TripStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTripStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TripStatus), nil
}

type UserRole string

const (
	UserRoleFleetManager     UserRole = "fleet_manager"
	UserRoleDriver           UserRole = "driver"
	UserRoleSafetyOfficer    UserRole = "safety_officer"
	UserRoleFinancialAnalyst UserRole = "financial_analyst"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type VehicleStatus string

const (
	VehicleStatusAvailable VehicleStatus = "Available"
	VehicleStatusOnTrip    VehicleStatus = "On Trip"
	VehicleStatusInShop    VehicleStatus = "In Shop"
	VehicleStatusRetired   VehicleStatus = "Retired"
)

func (e *VehicleStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VehicleStatus(s)
	case string:
		*e = VehicleStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for VehicleStatus: %T", src)
	}
	return nil
}

type NullVehicleStatus struct {
	VehicleStatus VehicleStatus
	Valid         bool // Valid is true if VehicleStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVehicleStatus) Scan(value interface{}) error {
	if value == nil {
		ns.VehicleStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VehicleStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVehicleStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VehicleStatus), nil
}

type Driver struct {
	ID                uuid.UUID
	UserID            uuid.NullUUID
	Name              string
	LicenseNumber     string
	LicenseCategory   string
	LicenseExpiryDate time.Time
	ContactNumber     string
	SafetyScore       sql.NullInt32
	Status            NullDriverStatus
	CreatedAt         sql.NullTime
}

type FuelLog struct {
	ID        uuid.UUID
	VehicleID uuid.NullUUID
	Liters    string
	Cost      string
	LogDate   time.Time
	CreatedAt sql.NullTime
}

type Trip struct {
	ID              uuid.UUID
	Source          string
	Destination     string
	VehicleID       uuid.NullUUID
	DriverID        uuid.NullUUID
	CargoWeight     string
	PlannedDistance string
	Status          NullTripStatus
	CreatedAt       sql.NullTime
}

type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	Role         UserRole
	CreatedAt    sql.NullTime
}

type Vehicle struct {
	ID                 uuid.UUID
	RegistrationNumber string
	NameModel          string
	VehicleType        string
	MaxLoadCapacity    string
	Odometer           sql.NullString
	AcquisitionCost    string
	Status             NullVehicleStatus
	CreatedAt          sql.NullTime
}
