// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trips.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createTrip = `-- name: CreateTrip :one
INSERT INTO trips (
    source, destination, vehicle_id, driver_id, cargo_weight, planned_distance
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, source, destination, vehicle_id, driver_id, cargo_weight, planned_distance, status, created_at
`

type CreateTripParams struct {
	Source          string
	Destination     string
	VehicleID       uuid.NullUUID
	DriverID        uuid.NullUUID
	CargoWeight     string
	PlannedDistance string
}

func (q *Queries) CreateTrip(ctx context.Context, arg CreateTripParams) (Trip, error) {
	row := q.db.QueryRowContext(ctx, createTrip,
		arg.Source,
		arg.Destination,
		arg.VehicleID,
		arg.DriverID,
		arg.CargoWeight,
		arg.PlannedDistance,
	)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.Destination,
		&i.VehicleID,
		&i.DriverID,
		&i.CargoWeight,
		&i.PlannedDistance,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updateTripStatus = `-- name: UpdateTripStatus :one
UPDATE trips
SET status = $2
WHERE id = $1
RETURNING id, source, destination, vehicle_id, driver_id, cargo_weight, planned_distance, status, created_at
`

type UpdateTripStatusParams struct {
	ID     uuid.UUID
	Status NullTripStatus
}

func (q *Queries) UpdateTripStatus(ctx context.Context, arg UpdateTripStatusParams) (Trip, error) {
	row := q.db.QueryRowContext(ctx, updateTripStatus, arg.ID, arg.Status)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.Destination,
		&i.VehicleID,
		&i.DriverID,
		&i.CargoWeight,
		&i.PlannedDistance,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
