// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vehicles.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createVehicle = `-- name: CreateVehicle :one
INSERT INTO vehicles (
    registration_number, name_model, vehicle_type, max_load_capacity, odometer, acquisition_cost
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, registration_number, name_model, vehicle_type, max_load_capacity, odometer, acquisition_cost, status, created_at
`

type CreateVehicleParams struct {
	RegistrationNumber string
	NameModel          string
	VehicleType        string
	MaxLoadCapacity    string
	Odometer           sql.NullString
	AcquisitionCost    string
}

func (q *Queries) CreateVehicle(ctx context.Context, arg CreateVehicleParams) (Vehicle, error) {
	row := q.db.QueryRowContext(ctx, createVehicle,
		arg.RegistrationNumber,
		arg.NameModel,
		arg.VehicleType,
		arg.MaxLoadCapacity,
		arg.Odometer,
		arg.AcquisitionCost,
	)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.RegistrationNumber,
		&i.NameModel,
		&i.VehicleType,
		&i.MaxLoadCapacity,
		&i.Odometer,
		&i.AcquisitionCost,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getAvailableVehicles = `-- name: GetAvailableVehicles :many
SELECT id, registration_number, name_model, vehicle_type, max_load_capacity, odometer, acquisition_cost, status, created_at FROM vehicles 
WHERE status = 'Available' AND max_load_capacity >= $1
`

func (q *Queries) GetAvailableVehicles(ctx context.Context, maxLoadCapacity string) ([]Vehicle, error) {
	rows, err := q.db.QueryContext(ctx, getAvailableVehicles, maxLoadCapacity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vehicle
	for rows.Next() {
		var i Vehicle
		if err := rows.Scan(
			&i.ID,
			&i.RegistrationNumber,
			&i.NameModel,
			&i.VehicleType,
			&i.MaxLoadCapacity,
			&i.Odometer,
			&i.AcquisitionCost,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVehicleStatus = `-- name: UpdateVehicleStatus :exec
UPDATE vehicles 
SET status = $2 
WHERE id = $1
`

type UpdateVehicleStatusParams struct {
	ID     uuid.UUID
	Status NullVehicleStatus
}

func (q *Queries) UpdateVehicleStatus(ctx context.Context, arg UpdateVehicleStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateVehicleStatus, arg.ID, arg.Status)
	return err
}
